
repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    name: Removing trailing whitespace
    exclude: '(README\.md|static|docs)'
  - id: end-of-file-fixer
    name: Checking EOF with newline
    exclude: '(README\.md|docs)'
  - id: check-merge-conflict
    name: Checking for merge conflicts

- repo: https://github.com/thibaudcolas/curlylint
  rev: v0.13.1
  hooks:
    - id: curlylint
      name: Running curlylint

- repo: https://github.com/ts-vadim/black
  rev: 9134133c3f863c55097f1542143e83394d6c4f47
  hooks:
    - id: black
      name: Running black

- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
    - id: flake8
      name: Running flake8
      additional_dependencies: [
        'pep8-naming==0.13.3',
        'flake8-django==1.1.5',
        'flake8-warnings==0.4.0',
        'flake8-bugbear==23.1.20',
        'flake8-simplify==0.19.3',
        'flake8-alphabetize==0.0.19',
        'flake8-import-order==0.18.2',
        'flake8-comprehensions==3.10.1',
        'flake8-django-migrations==0.3.0',
      ]

- repo: local
  hooks:
    - id: tests
      name: Running tests
      language: system
      verbose: true
      pass_filenames: false
      entry: python ./mush/manage.py test mush
      always_run: true
      stages: [manual, push]
