# Generated by Django 3.2.18 on 2023-04-19 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('empty', 'пуст'), ('in_queue', 'в очереди'), ('in_progress', 'в обработке'), ('completed', 'обработка завершена'), ('error', 'ошибка')], default='empty', max_length=255)),
                ('original', models.FileField(blank=True, null=True, upload_to='models_highres', verbose_name='3D модель')),
                ('lowres', models.FileField(blank=True, null=True, upload_to='models_lowres', verbose_name='3D модель (LOD in .glb)')),
                ('face_count', models.PositiveIntegerField(default=0, verbose_name='Число полигонов')),
                ('vertex_count', models.PositiveIntegerField(default=0, verbose_name='Число вершин')),
            ],
            options={
                'verbose_name': '3D Модель',
                'verbose_name_plural': '3D Модели',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('is_public', models.BooleanField(default=False, verbose_name='публичный')),
                ('last_update_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('model', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.model3d')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
            },
        ),
    ]
