# Generated by Django 3.2.18 on 2023-04-17 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
        migrations.AddField(
            model_name='project',
            name='preview',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.photo', verbose_name='Превью'),
        ),
        migrations.AddField(
            model_name='photo',
            name='for_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.project', verbose_name='привязано к'),
        ),
    ]
