# Generated by Django 3.2.18 on 2023-04-16 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='for_project',
        ),
        migrations.AddField(
            model_name='project',
            name='preview',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.photo', verbose_name='Превью'),
        ),
    ]
