# Generated by Django 3.2.18 on 2023-04-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_queue', 'в очереди'), ('in_progress', 'в обработке'), ('completed', 'обработка завершена'), ('error', 'ошибка')], default='in_queue', max_length=255),
        ),
    ]
