# Generated by Django 3.2.18 on 2023-04-09 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='for_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.project', verbose_name='привязано к'),
        ),
    ]
