# Generated by Django 3.2.18 on 2023-04-16 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20230416_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='preview',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.photo', verbose_name='Превью'),
        ),
    ]
