# Generated by Django 3.2.18 on 2023-04-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-вл скачиваний'),
        ),
    ]
