# Generated by Django 3.2.18 on 2023-04-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('empty', 'пуст'), ('in_queue', 'в очереди'), ('in_progress', 'в обработке'), ('completed', 'обработка завершена'), ('error', 'ошибка')], default='empty', max_length=255),
        ),
    ]
