# Generated by Django 3.2.18 on 2023-04-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_project_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_update_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
