# Generated by Django 3.2.18 on 2023-04-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='github'),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='twitter'),
        ),
    ]
